config/routes.rb
Shopper::Application.routes.draw do

  resources :item_catalog, only: [:index]
  resources :lists do
    resources :items
    resources :entries
  end

  root :to => 'lists#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :bought, :item_id, :list_id, :quantity, :item_attributes

  belongs_to :list, :autosave => true
  belongs_to :item

  accepts_nested_attributes_for :item, allow_destroy: true, reject_if: :all_blank

  def autosave_associated_records_for_item
    if new_item = Item.where("lower(name) LIKE lower(?)", item.name.strip).first
    # if new_item = Item.find_by_name(item.name)
      self.item = new_item
    end
    self.item.save!
    self.item_id = self.item.id
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :lowest_price, :last_price, :unit

  has_many :entries
  has_many :lists, :through => :entries
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  
  has_many :entries
  has_many :items, :through => :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  helper_method :list, :entry, :entries

  # GET /list/:list_id/entries
  # GET /list/:list_id/entries.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: entries }
    end
  end

  # GET /list/:list_id/entries/1
  # GET /list/:list_id/entries/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: entry }
    end
  end

  # GET /list/:list_id/entries/new
  # GET /list/:list_id/entries/new.json
  def new
    @entry = list.entries.build.tap do |entry|
      entry.item = Item.new
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: entry }
    end
  end

  # GET /list/:list_id/entries/1/edit
  def edit
  end

  # POST /list/:list_id/entries
  # POST /list/:list_id/entries.json
  def create
    @entry = list.entries.build(params[:entry])

    respond_to do |format|
      if entry.save
        format.html { redirect_to list, notice: 'Entry was successfully created.' }
        format.json { render json: entry, status: :created, location: [list, entry] }
      else
        format.html { render action: "new" }
        format.json { render json: entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list/:list_id/entries/1
  # PUT /list/:list_id/entries/1.json
  def update
    respond_to do |format|
      if entry.update_attributes(params[:entry])
        format.html { redirect_to list, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: entry.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /list/:list_id/entries/1
  # DELETE /list/:list_id/entries/1.json
  def destroy
    entry.destroy

    respond_to do |format|
      format.html { redirect_to list_entries_url(list) }
      format.json { head :no_content }
    end
  end

  protected

  def entries
    @entries = list.entries
  end

  def entry
    @entry ||= list.entries.find(params[:id]).tap do |entry|
      entry.item ||= Item.new
    end
  end

  def list
    @list ||= List.find(params[:list_id])
  end

end

app/controllers/item_catalog_controller.rb
class ItemCatalogController < ApplicationController

  respond_to :json, :html
  helper_method :items

  def index
    respond_with items
  end

  protected

  def items
    if params[:term].present?
      @items ||= Item.where("lower(name) LIKE lower(?)", "%#{params[:term]}%").order(:name)
    else
      Item.order(:name)
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  helper_method :entries, :list, :lists

  # GET /lists
  # GET /lists.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: list }
    end
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if list.save
        format.html { redirect_to list, notice: 'List was successfully created.' }
        format.json { render json: list, status: :created, location: list }
      else
        format.html { render action: "new" }
        format.json { render json: list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    respond_to do |format|
      if list.update_attributes(params[:list])
        format.html { redirect_to list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  protected

  def lists
    @lists ||= List.all
  end

  def list
    @list ||= List.find(params[:id])
  end

  def entries
    @entries ||= list.entries
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
#Display form for entering new list item
#On submit
#  look up in items to see if it already exits
#  if no
#    make a new item
#    give the option to add item detail
#  add entry to list
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/entries/_form.html.erb
<%= form_for([list, entry]) do |f| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b>Name:</b>
    <%= list.name %>
  </p>

  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.fields_for :item do |item_fields| %>
      <%= item_fields.text_field :name %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :bought %><br />
    <%= f.check_box :bought %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', list_entry_path(list, entry) %> |
<%= link_to 'Back', list_entries_path(list) %>

app/views/entries/index.html.erb
<h1>Shopping List for <%= list.name %></h1>

<table>
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Bought</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% entries.each do |entry| %>
  <tr>
    <td><%= entry.item ? entry.item.name : 'Unknown' %></td>
    <td><%= entry.quantity %></td>
    <td><%= entry.bought %></td>
    <td><%= link_to 'Show', list_entry_path(list, entry) %></td>
    <td><%= link_to 'Edit', edit_list_entry_path(list, entry) %></td>
    <td><%= link_to 'Destroy', list_entry_path(list, entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_list_entry_path(list) %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(list) %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= entry.list.name %>
</p>

<p>
  <b>Item:</b>
  <!-- entry.item.name -->
  <%= entry.item ? entry.item.name : ''%>
</p>

<p>
  <b>Quantity:</b>
  <%= entry.quantity %>
</p>

<p>
  <b>Bought:</b>
  <%= entry.bought %>
</p>


<%= link_to 'Edit', edit_list_entry_path(list, entry) %> |
<%= link_to 'Back', list_entries_path(list) %>

app/views/item_catalog/index.html.erb
<h1>Item Catalog</h1>
<ul>
  <% for item in items do %>
    <li><%= item.name %></li>
  <% end %>
</ul>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :lowest_price %><br />
    <%= f.text_field :lowest_price %>
  </p>
    <%= f.label :last_price %><br />
    <%= f.text_field :last_price %>
  </p>
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Item Index</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<ul>
  <li><b>Name:</b>
  <%= @item.name %></li>
  <li><b>Lowest Price: </b>
  $<%= @item.lowest_price.to_s %>/<%= @item.unit.to_s %></li>
  <li><b>Last Price: $</b>
  $<%= @item.last_price.to_s %>/<%= @item.unit.to_s %></li>
</ul>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Shopping Lists</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% lists.each do |list| %>
  <tr>
    <td><%= link_to list.name, list %></td>
    <td><%= link_to 'Edit', edit_list_path(list), class: "button tiny secondary" %></td>
    <td><%= link_to 'X', list, class: "button tiny secondary" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add A New List', new_list_path, class: "button small " %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= list.name %>
</p>

<table>
  <% entries.each do |entry| %>
    <tr>
      <td><%= entry.item ? entry.item.name : 'Unknown' %></td>
      <td><%= entry.quantity %></td>
      <td>
        <%= form_for [list, entry], remote: true do |f| %>
          <%= f.check_box :bought, class: "entry_bought" %>
        <% end %>
      </td>
      <!-- Remove show function, unnecessary
      <td><%= link_to 'Show', list_entry_path(list, entry) %></td> --> 
      <td><%= link_to 'Edit', edit_list_entry_path(list, entry), class: "button tiny secondary" %></td>
      <td><%= link_to 'X', list_entry_path(list, entry), class: "button tiny secondary", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Add New Entry', new_list_entry_path(list) %>
<%= link_to 'Edit', edit_list_path(list) %> |
<%= link_to 'Back', lists_path %>